### ISSUE TITLE
"No native build" is producing an error, should be a warning or info maybe

### ISSUE THREAD

**Issue by rapenne-s** [staltz/ssb-keys-neon#23]
When installing the software with npm on a system without a native build, the display shows an error and continue, with a fallback to build the rust program.

I think this shouldn't be reported as an error because it's not blocking the installation process.

```
$ npm install ssb-keys-neon

> ssb-keys-neon@8.0.0-8 install /home/test/node_modules/ssb-keys-neon
> neon-load-or-build

/home/test/node_modules/neon-load-or-build/index.js:62
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=openbsd arch=x64 runtime=node abi=72 uv=1 libc=glibc node=12.16.1
    loaded from: /home/test/node_modules/ssb-keys-neon

    at Function.load.path (/home/test/node_modules/neon-load-or-build/index.js:62:9)
    at load (/home/test/node_modules/neon-load-or-build/index.js:27:30)
    at Object.<anonymous> (/home/test/node_modules/neon-load-or-build/build-test.js:19:19)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

neon info forcing rebuild for new build settings
neon info running cargo
    Updating crates.io index
  Downloaded stream-cipher v0.4.1
[...]
```

**Comment by staltz** [comment]
I agree, but it's an issue at https://github.com/staltz/neon-load-or-build
