### ISSUE TITLE
On non native platform: get a ENOENT error after rust compilation

### ISSUE THREAD

**Issue by rapenne-s** [staltz/ssb-keys-neon#24]
Installing ssb-keys-neon with npm on OpenBSD amd64 produces an error after the rust compilation which seems to happens correctly.

```
kongroo$ npm install ssb-keys-neon

> ssb-keys-neon@8.0.0-8 install /home/test/node_modules/ssb-keys-neon
> neon-load-or-build

/home/test/node_modules/neon-load-or-build/index.js:62
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=openbsd arch=x64 runtime=node abi=72 uv=1 libc=glibc node=12.16.1
    loaded from: /home/test/node_modules/ssb-keys-neon

    at Function.load.path (/home/test/node_modules/neon-load-or-build/index.js:62:9)
    at load (/home/test/node_modules/neon-load-or-build/index.js:27:30)
    at Object.<anonymous> (/home/test/node_modules/neon-load-or-build/build-test.js:19:19)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

neon info forcing rebuild for new build settings
neon info running cargo
    Updating crates.io index
  Downloaded stream-cipher v0.4.1
  Downloaded aho-corasick v0.7.6
  Downloaded cc v1.0.50
  Downloaded opaque-debug v0.3.0
  Downloaded semver v0.9.0
  Downloaded curve25519-dalek v3.0.0
  Downloaded semver-parser v0.7.0
  Downloaded serde v1.0.116
  Downloaded serde_derive v1.0.116
  Downloaded quote v1.0.2
  Downloaded thiserror v1.0.20
  Downloaded typenum v1.12.0
  Downloaded universal-hash v0.4.0
  Downloaded zerocopy v0.3.0
  Downloaded signature v1.2.2
  Downloaded zeroize v1.1.1
  Downloaded zeroize_derive v1.0.1
  Downloaded aead v0.3.2
  Downloaded cslice v0.2.0
  Downloaded base64 v0.12.3
  Downloaded cpuid-bool v0.1.2
  Downloaded crypto-mac v0.9.1
  Downloaded block-buffer v0.9.0
  Downloaded digest v0.9.0
  Downloaded generic-array v0.14.4
  Downloaded hmac v0.9.0
  Downloaded itoa v0.4.5
  Downloaded poly1305 v0.6.0
  Downloaded neon-runtime v0.5.1
  Downloaded ppv-lite86 v0.2.9
  Downloaded ed25519 v1.0.2
  Downloaded proc-macro2 v1.0.21
  Downloaded rand_chacha v0.2.2
  Downloaded ed25519-dalek v1.0.1
  Downloaded rand_core v0.5.1
  Downloaded neon-build v0.5.1
  Downloaded subtle v2.3.0
  Downloaded sha2 v0.9.1
  Downloaded synstructure v0.12.4
  Downloaded thiserror-impl v1.0.20
  Downloaded arrayvec v0.5.1
  Downloaded version_check v0.9.2
  Downloaded base64 v0.11.0
  Downloaded cfg-if v0.1.10
  Downloaded salsa20 v0.5.2
  Downloaded byteorder v1.3.4
  Downloaded ryu v1.0.2
  Downloaded unicode-xid v0.2.0
  Downloaded smallvec v1.4.2
  Downloaded xsalsa20poly1305 v0.4.2
  Downloaded thread_local v1.0.1
  Downloaded getrandom v0.1.15
  Downloaded lazy_static v1.4.0
  Downloaded memchr v2.3.0
  Downloaded neon-sys v0.5.1
  Downloaded ssb-crypto v0.2.1
  Downloaded ssb-keyfile v0.4.0
  Downloaded private-box v0.6.0
  Downloaded serde_json v1.0.45
  Downloaded rand v0.7.3
  Downloaded x25519-dalek v1.1.0
  Downloaded neon v0.5.1
  Downloaded regex-syntax v0.6.13
  Downloaded syn v1.0.41
  Downloaded regex v1.3.3
  Downloaded libc v0.2.66
  Downloaded zerocopy-derive v0.2.0
  Downloaded 67 crates (3.9 MB) in 4.63s
   Compiling proc-macro2 v1.0.21
   Compiling unicode-xid v0.2.0
   Compiling version_check v0.9.2
   Compiling typenum v1.12.0
   Compiling syn v1.0.41
   Compiling cfg-if v0.1.10
   Compiling memchr v2.3.0
   Compiling lazy_static v1.4.0
   Compiling libc v0.2.66
   Compiling regex-syntax v0.6.13
   Compiling subtle v2.3.0
   Compiling cc v1.0.50
   Compiling getrandom v0.1.15
   Compiling byteorder v1.3.4
   Compiling ppv-lite86 v0.2.9
   Compiling serde_derive v1.0.116
   Compiling signature v1.2.2
   Compiling cpuid-bool v0.1.2
   Compiling opaque-debug v0.3.0
   Compiling ryu v1.0.2
   Compiling serde v1.0.116
   Compiling base64 v0.12.3
   Compiling semver-parser v0.7.0
   Compiling itoa v0.4.5
   Compiling cslice v0.2.0
   Compiling smallvec v1.4.2
   Compiling base64 v0.11.0
   Compiling arrayvec v0.5.1
   Compiling neon-build v0.5.1
   Compiling thread_local v1.0.1
   Compiling generic-array v0.14.4
   Compiling ed25519 v1.0.2
   Compiling semver v0.9.0
   Compiling quote v1.0.2
   Compiling aho-corasick v0.7.6
   Compiling regex v1.3.3
   Compiling rand_core v0.5.1
   Compiling digest v0.9.0
   Compiling stream-cipher v0.4.1
   Compiling block-buffer v0.9.0
   Compiling universal-hash v0.4.0
   Compiling crypto-mac v0.9.1
   Compiling aead v0.3.2
   Compiling synstructure v0.12.4
   Compiling rand_chacha v0.2.2
   Compiling sha2 v0.9.1
   Compiling poly1305 v0.6.0
   Compiling hmac v0.9.0
   Compiling rand v0.7.3
   Compiling neon-sys v0.5.1
   Compiling zeroize_derive v1.0.1
   Compiling zerocopy-derive v0.2.0
   Compiling thiserror-impl v1.0.20
   Compiling zeroize v1.1.1
   Compiling neon-runtime v0.5.1
   Compiling curve25519-dalek v3.0.0
   Compiling salsa20 v0.5.2
   Compiling neon v0.5.1
   Compiling ssb-keys-neon v8.0.0 (/home/test/node_modules/ssb-keys-neon/native)
   Compiling ed25519-dalek v1.0.1
   Compiling x25519-dalek v1.1.0
   Compiling zerocopy v0.3.0
   Compiling xsalsa20poly1305 v0.4.2
   Compiling thiserror v1.0.20
   Compiling ssb-crypto v0.2.1
   Compiling private-box v0.6.0
   Compiling serde_json v1.0.45
   Compiling ssb-keyfile v0.4.0
    Finished release [optimized] target(s) in 4m 31s
neon info generating native/index.node
neon ERR! ENOENT: no such file or directory, copyfile '/home/test/node_modules/ssb-keys-neon/native/target/release/undefinedssb_neon_keysundefined' -> '/home/test/node_modules/ssb-keys-neon/native/index.node'

Error: ENOENT: no such file or directory, copyfile '/home/test/node_modules/ssb-keys-neon/native/target/release/undefinedssb_neon_keysundefined' -> '/home/test/node_modules/ssb-keys-neon/native/index.node'
npm WARN enoent ENOENT: no such file or directory, open '/home/test/package.json'
npm WARN ssb-conn@0.16.2 requires a peer of secret-stack@>=6.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ssb-keys-neon@8.0.0-8 install: `neon-load-or-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssb-keys-neon@8.0.0-8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/test/.npm/_logs/2020-11-06T07_51_13_664Z-debug.log
```

**Comment by staltz** [comment]
Can you try git cloning this repo, then running `npm install` and `npm test`?

**Comment by rapenne-s** [comment]
This gives me the same result.
If this can help you, I may be able to provide a shell access to such machine.

**Comment by staltz** [comment]
@rapenne-s I can't ssh now to debug this, but I suspect it's a general problem with `neon` on such machines. I recommend trying another neon project (or just starting the template project with neon CLI) and then maybe this leads to opening an issue at https://github.com/neon-bindings/neon 

This is because my suspicion of the `copyfile` ENOENT error is that it seems like it comes from Neon.

**Comment by rapenne-s** [comment]
I can reproduce the issue with an empty neon project.
Filling an issue upstream.
